version: "3.9"
services:
  app:
    build:
      context: .
    volumes:
      - static-data:/vol/web

  proxy:
    build:
      context: ./proxy
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static

volumes:
  static-data:
