version: "3.9"
services:
  app:
    build:
      context: .
    volumes:
      - static-data:/vol/web

  proxy:
    build:
      context: ./proxy
    depends_on:
      - app
    ports:
      - 8000:8000
    volumes:
      - static-data:/vol/static

  celery:
    build: .
    command: celery --app=PipeDriveAutomation.celery:app worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - app
      - redis
    network_mode: "host"  # Add this line

  redis:
    image: redis:alpine
    network_mode: "host"  # Add this line

volumes:
  static-data:
