version: "3.9"

services:
  db:
    image: postgres:latest
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    env_file:
      - .env

  celery:
    build: .
    command: celery --app=PipeDriveAutomation.celery:app worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - app
      - redis
      - db
    env_file:
      - .env

  redis:
    image: redis:alpine

volumes:
  dev-db-data: