# Generated by Django 5.0 on 2023-12-28 22:51

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('scopes', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypted_password', encrypted_model_fields.fields.EncryptedCharField(default='')),
            ],
        ),
    ]
