# Generated by Django 5.0 on 2023-12-31 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_platformintegration_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipedriveWebhook',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('event_object', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_last_called', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.platformintegration')),
            ],
        ),
    ]
