# Generated by Django 5.0 on 2024-02-05 23:38

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=255)),
                ('company_id', models.CharField(max_length=255)),
                ('password', encrypted_model_fields.fields.EncryptedCharField(default='')),
                ('url', models.URLField()),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('event_object', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_last_called', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.platformintegration')),
            ],
        ),
    ]
