# Generated by Django 5.0 on 2024-01-31 20:04

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipedrive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipedrivewebhook',
            name='company_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipedrivewebhook',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(default=''),
        ),
    ]
