# Generated by Django 5.0 on 2023-12-26 19:58

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipedriveIntegration',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_management.company')),
                ('is_authenticated', models.BooleanField(default=False)),
                ('pipedrive_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('scopes', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypted_password', encrypted_model_fields.fields.EncryptedCharField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PipedriveWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField()),
                ('webhook_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('event_object', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipedrive.pipedriveintegration')),
            ],
        ),
    ]
