# Generated by Django 4.2.6 on 2023-12-11 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0002_company_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipedriveIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authenticated', models.BooleanField(default=False)),
                ('pipedrive_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('scopes', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.company')),
            ],
        ),
        migrations.CreateModel(
            name='PipedriveWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_url', models.URLField()),
                ('webhook_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipedrive.pipedriveintegration')),
            ],
        ),
    ]
