# Generated by Django 5.0 on 2023-12-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipedrive', '0001_initial'),
        ('user_management', '0002_company_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipedriveintegration',
            name='id',
        ),
        migrations.AlterField(
            model_name='pipedriveintegration',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user_management.company'),
        ),
    ]
