# Generated by Django 5.0 on 2023-12-28 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pipedrive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipedrivewebhook',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.platformintegration'),
        ),
        migrations.DeleteModel(
            name='PipedriveIntegration',
        ),
    ]
