# Generated by Django 5.0 on 2024-02-05 23:38

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformIntegration',
            fields=[
                ('platform', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('scopes', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('refresh_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
            ],
        ),
    ]
