# Generated by Django 5.0 on 2023-12-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_platformintegration_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformintegration',
            name='id',
        ),
        migrations.AlterField(
            model_name='platformintegration',
            name='platform',
            field=models.CharField(default=1, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
