# Generated by Django 5.0 on 2024-01-31 20:04

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_platformintegration_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformintegration',
            name='encrypted_password',
        ),
        migrations.AddField(
            model_name='platformintegration',
            name='access_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformintegration',
            name='refresh_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
